### ISSUE TITLE
对第三节定义的疑惑

### ISSUE THREAD

**Issue by mrl998** [Einzithy-D/Arknights_Stats#1]
首先感谢大佬的数据分析工作！
在分析垫刀问题的过程中，我们关注的原问题是“**出货（触发加成）一次后**，接着连续n次不出货后，出货概率是否会变化”。
文中第三节中定义pn=P(Xt=1|Xt-1=0,...,Xt-n=0)，这个定义并没有保证Xt-n-1=1，与我们原问题有一些差异。
对应第四节中，计算p2=#[0,0,1]/#[0,0]。而参照原问题，是否该计算p2=#[1,0,0,1]/#[1,0,0]更加准确？
最后我尝试利用http://nga.178.com/read.php?tid=17676887 中的400条数据，计算上述两个定义对应的p1、p2、p3，发现两者有不小的差距，请问是哪里出现了问题呢？
感谢阅读，希望能够答疑XD

**Comment by Einzithy-D** [comment]
这是因为你对垫刀定义和我的不一样。我认为原问题不带所谓的【触发过一次加成】这个判断。
原因是这样问题就带上了初始条件，那么新号的加成判断怎么考虑。

当然，不能否认这种可能。于是，我试了一下你说的定义方式，如果按照你的定义，使用形如 #[1, (n-1个0), 1] 和 #[1,(n-10)], n = 1,2... 的序列。发现样本数量会大幅减少【因为对序列要求更高了】使得最后结果的标准差很大【在均值周围波动很强烈】。虽然最终结论还是一致的，不存在垫刀存在的证据。但此时由于样本量太小带来的标准差很大，频率学派的表格看起来就不直观。不能只看均值，要再跟着看标准差的区间了。

举个例子，在你的定义下，【0刀保底】序列为 #[11] (样本10) 占 #[1] (样本73)的比例, CLT 均值在0.137，标准差在0.0402. 那么考虑5%的置信水平，近似 均值±2*标准差，interval到了 [ 0.0566, 0.2174]。【1刀保底】序列为 #[101](样本13)占 #[10](样本63) 的比例，CLT均值在0.206，标准差在0.0509. 同样5%的置信水平下，近似 均值±2*标准差，interval在 [ 0.1042, 0.3078]. 虽然你单看均值可能觉得这两个数值差很大。但考虑到标准差，实际上区间有着极大的重合。

这种频率派的表格可能很难直接看出来的情况需要考虑p值。p.value 矩阵所有p值都至少在0.2（20%）以上。说明无法拒绝原假设，无法否认分布概率不等。（即使不存在垫刀证据）

但样本量过小时，chisq检验对离散的近似可能不准确，使得部分高n垫刀情况下结论可能会有偏差【虽然所有的结论都是不存在垫刀】。于是再考虑贝叶斯派方法，同样95%置信区间包含0点，无法否认分布概率不等。（不存在垫刀证据）。

综上，结论于之前一直，不存在说明垫刀的证据。可复现代码更新在 MS_diff_def.R 里面了。如果发现code里面有bug可以反馈。



> 首先感谢大佬的数据分析工作！
> 在分析垫刀问题的过程中，我们关注的原问题是“**出货（触发加成）一次后**，接着连续n次不出货后，出货概率是否会变化”。
> 文中第三节中定义pn=P(Xt=1|Xt-1=0,...,Xt-n=0)，这个定义并没有保证Xt-n-1=1，与我们原问题有一些差异。
> 对应第四节中，计算p2=#[0,0,1]/#[0,0]。而参照原问题，是否该计算p2=#[1,0,0,1]/#[1,0,0]更加准确？
> 最后我尝试利用http://nga.178.com/read.php?tid=17676887 中的400条数据，计算上述两个定义对应的p1、p2、p3，发现两者有不小的差距，请问是哪里出现了问题呢？
> 感谢阅读，希望能够答疑XD

**Comment by mrl998** [comment]
@Einzithy-D 感谢答疑！
